### ISSUE TITLE
Infinite loop/Stuck at registering/authorization 

### ISSUE THREAD

**Issue by NihalNavath** [mikenikles/your-analytics#274]
**Describe the bug**
I am stuck at this page - https://www.your-analytics.org/auth, after entering my email address, it does shows the "Check you email" popup and clicking on the link that is emailed just reloads to the same page instead of registering, further submissions are not accepted and pressing on the "Sign in" button just clears out the email field. I have tried registering using a private tab, but same fate.

**To Reproduce**
1. Go to https://www.your-analytics.org/auth
2. Provide email address
3. Accept email address
4. Page reloads without any change, thus putting you in an infinite loop

**Expected behavior**
Proceed to the next page

**Desktop (please complete the following information) - Optional:**
 - OS: Windows 10
 - Browser: Microsoft edge 
 - Version: Version 92.0.902.67 (Official build) (64-bit)

**Additional context - Optional**
Addition note- I do use pi-hole (https://pi-hole.net), I tried disabling it but problem still exists.

Trying to answer some question that you guys might ask/have-

1) Is the sign in page kept opened-
yes the page is kept open
2) Any errors/warning in console-
No nothing 
3) What happens after you click on the link that is emailed to you?
After clicking, it shows this page "You're now logged into your Analytics! you can now close this window", and on returning to the analytics sign in page simple reloads.
3) Try in incognito/other browsers-
Nope, no luck same fate even when tried on different browsers and/or private tabs :/

**Comment by mikenikles** [comment]
Hi Nihal, thanks for reporting this. I can confirm this is a bug and unfortunately impacts all users of Your Analytics.

I reached out to the folks at https://magic.link - the authentication service I use for Your Analytics. What's odd is I can't log in to their website either at the moment, although [their status page](https://status.magic.link/) does not currently indicate any service disruption.

Their support team will be available at 9am PST (in 12 hours). I will continue the conversation with them and post updates here when I know more.

My apologies for the inconvenience!

On a slightly brighter note: If you have Your Analytics already installed on your website, capturing data is not impacted and if your dashboard is publicly shared, you can continue to access that too.

**Comment by mikenikles** [comment]
Hi Nihal,

That's fixed now. I recently moved the project from a team Vercel account to a personal account. In that process, two environment variables didn't get migrated properly.

Cheers,

Mike
