### ISSUE TITLE
Can't install owa...

### ISSUE THREAD

**Issue by Noeppes** [mikenikles/your-analytics#293]
I've downloaded  owa in actually version and install it. But install send only a blank screen. Also manual install - after put all data in conf-file -> blank screen.
Why?
I have an older Version  (2-3 Years old). That can I install with install.php without Problems...

The second is the downloaded ZIP-File, after decompressing i have many Files double in a Directory called Open-Web-Analytics-master and many dirs like .git... - Why?
And nothing in log-files!

**Comment by mikenikles** [comment]
That sounds like it's a different project. The code for Your Analytics is written in JavaScript and doesn't contain any PHP.

I'm closing this, but you can re-open the issue at the owa repository at https://github.com/Open-Web-Analytics/Open-Web-Analytics.
